services:
  redis-like:
    build:
      context: ../redis-like
      dockerfile: Dockerfile.redis
    expose: ["4000"]
    networks: [internal]

  api:
    build:
      context: .
      dockerfile: Dockerfile.kv
    ports: ["8080:3000"]
    environment:
      REDIS_URL: http://redis-like:4000
    depends_on: [redis-like]
    networks: [internal]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/kv/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks: 
  internal: